### ISSUE TITLE
And how to test it with that flow?

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer-analyze-css#3]
/cc @RobLoach lol

**Comment by RobLoach** [comment]
Hmm? What do you mean?

**Comment by tunnckoCore** [comment]
I mean, go try to write tests for it. Cuz im absolutely confused about that testing, boilerplate spam and organization path, at all :D

**Comment by RobLoach** [comment]
:+1:

> boilerplate spam

If you think Boilerplate is spam, then fix it: https://github.com/jstransformers/boilerplate .

> Write tests

https://github.com/jstransformers/jstransformer-analyze-css/issues/4

test-transformer supports multiple tests in different folders.

**Comment by tunnckoCore** [comment]
:+1:
